// Code generated by MockGen. DO NOT EDIT.
// Source: jwt_manager_interface.go
//
// Generated by this command:
//
//	mockgen -source=jwt_manager_interface.go -destination=../../test/mock/pkg/token/jwt_manager_mock.go -package=token_mock
//

// Package token_mock is a generated GoMock package.
package token_mock

import (
	reflect "reflect"
	time "time"

	token "github.com/fajar3108/lms-backend/pkg/token"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTManagerInterface is a mock of JWTManagerInterface interface.
type MockJWTManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJWTManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockJWTManagerInterfaceMockRecorder is the mock recorder for MockJWTManagerInterface.
type MockJWTManagerInterfaceMockRecorder struct {
	mock *MockJWTManagerInterface
}

// NewMockJWTManagerInterface creates a new mock instance.
func NewMockJWTManagerInterface(ctrl *gomock.Controller) *MockJWTManagerInterface {
	mock := &MockJWTManagerInterface{ctrl: ctrl}
	mock.recorder = &MockJWTManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTManagerInterface) EXPECT() *MockJWTManagerInterfaceMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTManagerInterface) GenerateAccessToken(userID string) (string, string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(time.Time)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTManagerInterfaceMockRecorder) GenerateAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTManagerInterface)(nil).GenerateAccessToken), userID)
}

// GenerateRefreshToken mocks base method.
func (m *MockJWTManagerInterface) GenerateRefreshToken(userID string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJWTManagerInterfaceMockRecorder) GenerateRefreshToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJWTManagerInterface)(nil).GenerateRefreshToken), userID)
}

// VerifyToken mocks base method.
func (m *MockJWTManagerInterface) VerifyToken(tokenStr string) (*token.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenStr)
	ret0, _ := ret[0].(*token.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockJWTManagerInterfaceMockRecorder) VerifyToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockJWTManagerInterface)(nil).VerifyToken), tokenStr)
}
