// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service_interface.go
//
// Generated by this command:
//
//	mockgen -source=auth_service_interface.go -destination=../../test/mock/auth/auth_service_mock.go -package=auth_mock
//

// Package auth_mock is a generated GoMock package.
package auth_mock

import (
	context "context"
	reflect "reflect"

	auth "github.com/fajar3108/lms-backend/internal/auth"
	user "github.com/fajar3108/lms-backend/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterace is a mock of AuthServiceInterace interface.
type MockAuthServiceInterace struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInteraceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInteraceMockRecorder is the mock recorder for MockAuthServiceInterace.
type MockAuthServiceInteraceMockRecorder struct {
	mock *MockAuthServiceInterace
}

// NewMockAuthServiceInterace creates a new mock instance.
func NewMockAuthServiceInterace(ctrl *gomock.Controller) *MockAuthServiceInterace {
	mock := &MockAuthServiceInterace{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInteraceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterace) EXPECT() *MockAuthServiceInteraceMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockAuthServiceInterace) GetProfile(ctx context.Context, userID string) (*user.UserResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*user.UserResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockAuthServiceInteraceMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockAuthServiceInterace)(nil).GetProfile), ctx, userID)
}

// Login mocks base method.
func (m *MockAuthServiceInterace) Login(ctx context.Context, req *auth.LoginRequest) (*user.LoginResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*user.LoginResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInteraceMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterace)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockAuthServiceInterace) Logout(ctx context.Context, userID, sessionID, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, userID, sessionID, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInteraceMockRecorder) Logout(ctx, userID, sessionID, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterace)(nil).Logout), ctx, userID, sessionID, refreshToken)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceInterace) RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest) (*user.LoginResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(*user.LoginResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceInteraceMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceInterace)(nil).RefreshToken), ctx, req)
}

// Register mocks base method.
func (m *MockAuthServiceInterace) Register(ctx context.Context, req *auth.RegisterRequest) (*user.UserResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*user.UserResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceInteraceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceInterace)(nil).Register), ctx, req)
}
